version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usdt_parser
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"

  app:
    build: .
    ports:
      - "50051:50051"
    environment:
      APP_DB_HOST: postgres
      APP_DB_PORT: "5432"
      APP_DB_USER: postgres
      APP_DB_PASSWORD: postgres
      APP_DB_NAME: usdt_parser
      APP_DB_SSLMODE: disable
      APP_GRPC_PORT: "50051"
      APP_OTEL_ENDPOINT: jaeger:4317
      APP_OTEL_INSECURE: "true"
      APP_LOG_DEV: "true"
    depends_on:
      postgres:
        condition: service_healthy
      jaeger:
        condition: service_started

volumes:
  pgdata:
